### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by michaldaniel** [superjohan/jmlcollection#11]
Hi.
I have a quick question. I'm wondering:
Does Apache 2.0 License also cover entries in /jmlcollection ?

**Comment by superjohan** [comment]
That's a good question. All my demos are licensed with the Apache license, but I doubt that the others are. (@psonice can answer regarding their demo)

The idea, such as it is, is that the app itself is covered by the license, but not the content. That's not made very clear, though. I should figure out how to make it clear in either the license file itself or the readme.

**Comment by michaldaniel** [comment]
While it technically looked like LICENSE covers everything I suspected as much. I think it's good idea to append copyright and proper license header/exclusion notice to top of content .js and .html files.

Otherwise someone might get the idea to make Android app using it. 😁

**Comment by superjohan** [comment]
To be honest I don't think anyone involved would mind having their demo embedded in an Android app. :) All the web stuff is already freely available on the web anyway. (pouet, etc)

**Comment by michaldaniel** [comment]
I was considering web stuff only anyway as putting that together requires next to zero work and it irked me wrong way thinking that art is tied to a single closed platform. Seeing swift code in there though makes it more understandable.

**Comment by superjohan** [comment]
Only the native iOS demos are tied to iOS. All the others are freely downloadable elsewhere. :)

**Comment by psonice** [comment]
Assume if I’ve put source up there I don’t particularly give a fuck, and do what you want :) Although my demo is probably the least portable, being metal and swift. 

Chris

**Comment by michaldaniel** [comment]
Glad to hear that, and that is why I'm going to leave it be. Still thou, building a platform like that it might be a good idea to figure out licensing and copyright scheme just in case some fucks are given. 😂
